This project is a Machine Learning-based application that classifies Python code snippets into skill levels (Beginner, Intermediate, Advanced) using NLP techniques like TF-IDF and multiple classification models.
It also includes a Streamlit web app that allows users to input code and get real-time skill level predictions using the best-performing trained model.

In [4]:
# Core libraries
import pandas as pd
import re

# Sklearn modules
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB

# Evaluation metrics
from sklearn.metrics import accuracy_score, classification_report

step 1:Loading the Dataset

In [5]:
df =pd.read_excel("C:/Users/chand/OneDrive - Indian School of Business/Documents/AI_PROJECT.xlsx")
df.head()

                                                CODE     SKILL
0                   for i in range(5):\n    print(i)  Beginner
1   a = int(input())\nb = int(input())\nprint(a + b)  Beginner
2  numbers = [1, 2, 3, 4]\nfor n in numbers:\n   ...  Beginner
3                        a = 5\nb = 2\nprint(a // b)  Beginner
4  num1 = "5"\nnum2 = 3\nresult = num1 * num2\npr...  Beginner

step2: Checking the Dataset

In [6]:
df.columns

Index(['CODE', 'SKILL'], dtype='object')

In [7]:
df['SKILL'].value_counts()

SKILL
Advanced        41
Intermediate    33
Beginner        28
intermediate     6
beginner         1
Name: count, dtype: int64

Step3:Preprocessing

In [8]:
def clean_code(text):
    text=text.lower()
    text=re.sub(r"\s+", " ", text)  # remove extra spaces
    return text

df['code_clean']=df['CODE'].apply(clean_code)
df.head()

,CODE,SKILL,code_clean
0,for i in range(5):\n print(i),Beginner,for i in range(5): print(i)
1,a = int(input())\nb = int(input())\nprint(a + b),Beginner,a = int(input()) b = int(input()) print(a + b)
2,"numbers = [1, 2, 3, 4]\nfor n in numbers:\n ...",Beginner,"numbers = [1, 2, 3, 4] for n in numbers: print(n)"
3,a = 5\nb = 2\nprint(a // b),Beginner,a = 5 b = 2 print(a // b)
4,"num1 = ""5""\nnum2 = 3\nresult = num1 * num2\npr...",Beginner,"num1 = ""5"" num2 = 3 result = num1 * num2 print..."

Step4:Spliting data into Train data and Test Data

In [9]:
X = df['code_clean']
y = df['SKILL']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

step5:Converting Text to Numbers

In [10]:
vectorizer=TfidfVectorizer(analyzer="char", ngram_range=(2, 5))
X_train_vec=vectorizer.fit_transform(X_train)
X_test_vec=vectorizer.transform(X_test)

Step 6:TRAINING FUNCTION

In [13]:
def train_and_evaluate(model, X_train, y_train, X_test, y_test, name):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)

    print("\n======================")
    print(name)
    print("Accuracy:", acc)
    print(classification_report(y_test, y_pred, zero_division=0))

    return model, acc

step 7:Model Training

In [14]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=500, class_weight="balanced"),
    "SVM": SVC(class_weight="balanced"),
    "Random Forest": RandomForestClassifier(n_estimators=100, class_weight="balanced"),
    "Naive Bayes": MultinomialNB()
}

results = {}
trained_models = {}

for name, model in models.items():
    trained_model, acc = train_and_evaluate(
        model,
        X_train_vec,
        y_train,
        X_test_vec,
        y_test,
        name
    )

    results[name] = acc
    trained_models[name] = trained_model

======================
Logistic Regression
Accuracy: 0.8181818181818182
              precision    recall  f1-score   support

    Advanced       0.83      1.00      0.91        10
    Beginner       0.75      1.00      0.86         6
Intermediate       1.00      0.50      0.67         4
intermediate       0.00      0.00      0.00         2

    accuracy                           0.82        22
   macro avg       0.65      0.62      0.61        22
weighted avg       0.77      0.82      0.77        22


======================
SVM
Accuracy: 0.8636363636363636
              precision    recall  f1-score   support

    Advanced       1.00      0.90      0.95        10
    Beginner       0.75      1.00      0.86         6
Intermediate       0.80      1.00      0.89         4
intermediate       0.00      0.00      0.00         2

    accuracy                           0.86        22
   macro avg       0.64      0.72      0.67        22
weighted avg       0.80      0.86      0.83        22


======================
Random Forest
Accuracy: 0.7272727272727273
              precision    recall  f1-score   support

    Advanced       0.86      0.60      0.71        10
    Beginner       0.86      1.00      0.92         6
Intermediate       0.50      1.00      0.67         4
intermediate       0.00      0.00      0.00         2

    accuracy                           0.73        22
   macro avg       0.55      0.65      0.57        22
weighted avg       0.71      0.73      0.69        22


======================
Naive Bayes
Accuracy: 0.8181818181818182
              precision    recall  f1-score   support

    Advanced       0.83      1.00      0.91        10
    Beginner       0.75      1.00      0.86         6
Intermediate       1.00      0.50      0.67         4
intermediate       0.00      0.00      0.00         2

    accuracy                           0.82        22
   macro avg       0.65      0.62      0.61        22
weighted avg       0.77      0.82      0.77        22

In [ ]:
Step 8: BEST MODEL SELECTION

In [15]:
best_model_name = max(results, key=results.get)
best_model = trained_models[best_model_name]

print("\n======================")
print("BEST MODEL:", best_model_name)
print("BEST ACCURACY:", results[best_model_name])

======================
BEST MODEL: SVM
BEST ACCURACY: 0.8636363636363636

step9:Testing

In [18]:
def predict_level(code_snippet):
    cleaned = clean_code(code_snippet)
    vec = vectorizer.transform([cleaned])
    return best_model.predict(vec)[0]

In [21]:
user_code=input("Enter your code snippet: ")
print("Predicted Level:", predict_level(user_code))

Enter your code snippet:  num = 10  if num % 2 == 0:     print("Even") else:     print("Odd")

Predicted Level: Beginner

In [22]:
user_code=input("Enter your code snippet: ")
print("Predicted Level:", predict_level(user_code))

Enter your code snippet:  def msg(name):     return f"Hello, {name}!"  # Assigning the function to a variable f = msg  # Calling the function using the variable print(f("Emma"))

Predicted Level: Intermediate

In [25]:
import joblib
joblib.dump(best_model, "code_level_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']

step9: creating Streamlit App File

In [25]:
!pip install streamlit

Requirement already satisfied: streamlit in c:\users\chand\anaconda3\lib\site-packages (1.45.1)
Requirement already satisfied: altair<6,>=4.0 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (8.1.8)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging<25,>=20 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<12,>=7.1.0 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (11.1.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (19.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\chand\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\chand\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\chand\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\chand\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (1.31.0)
Requirement already satisfied: colorama in c:\users\chand\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\chand\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\chand\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\chand\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\chand\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\chand\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\chand\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\chand\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\chand\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\chand\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.10.5)
Requirement already satisfied: attrs>=22.2.0 in c:\users\chand\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\chand\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\chand\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\chand\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)
Requirement already satisfied: six>=1.5 in c:\users\chand\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\chand\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)

In [26]:
%%writefile app.py
import streamlit as st
import joblib
import re

model = joblib.load("code_level_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

def clean_code(text):
    text = text.lower()
    text = re.sub(r"\s+", " ", text)
    return text

def predict_level(code_snippet):
    cleaned = clean_code(code_snippet)
    vec = vectorizer.transform([cleaned])
    return model.predict(vec)[0]

st.title("🧠 Code Skill Level Predictor")

st.write("Enter a Python code snippet and get predicted skill level")

code_input = st.text_area("Paste your code here:", height=200)

if st.button("Predict"):
    if code_input.strip() == "":
        st.error("Please enter code!")
    else:
        prediction = predict_level(code_input)
        st.success(f"Predicted Level: {prediction}")

Overwriting app.py

In [ ]:
!streamlit run app.py